/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;

import java.util.Date;

import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


import java.sql.ResultSet;
import java.sql.SQLException;
import processdata.ConnectDatabase;
import processdata.ImportToDatabase;
/**
 *
 * @author Admin
 */
public class demogiaodien extends javax.swing.JFrame {

    /**
     * Creates new form demogiaodien
     */
    public demogiaodien() {
        initComponents();
        jButton1.setText(toTwodaybefore());
        jButton2.setText(toYesterday());
        jButton4.setText(toDay());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        ndtimkiem = new javax.swing.JLabel();
        addbutton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ndtimkiem1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("thông tin cổ phiếu");
        setBackground(new java.awt.Color(0, 255, 204));

        ndtimkiem.setBackground(new java.awt.Color(102, 204, 255));
        ndtimkiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ndtimkiem.setForeground(new java.awt.Color(0, 153, 51));
        ndtimkiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ndtimkiem.setText("NỘI DUNG TÌM KIẾM");
        ndtimkiem.setOpaque(true);

        addbutton.setBackground(new java.awt.Color(102, 102, 0));
        addbutton.setForeground(new java.awt.Color(204, 204, 255));
        addbutton.setText("data");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(153, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));

        ndtimkiem1.setBackground(new java.awt.Color(102, 204, 255));
        ndtimkiem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ndtimkiem1.setForeground(new java.awt.Color(0, 153, 51));
        ndtimkiem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ndtimkiem1.setText("TÌM KIẾM MÃ");
        ndtimkiem1.setOpaque(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "TP.Hồ Chí Minh", "UPCOM" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Chọn sàn:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Chọn mã:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Chọn ngày:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        this.setMa_CP("select Ma_CP from So_Lieu_Giao_Dich where San_GD = 'HNX'");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            this.Ma_CP,
            new String [] {
                "Mã Cổ Phiếu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTable1);
        jTable1.setCellSelectionEnabled(true);
        ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String selectedData = null;

                int[] selectedRow = jTable1.getSelectedRows();
                int[] selectedColumns = jTable1.getSelectedColumns();

                for (int i = 0; i < selectedRow.length; i++) {
                    for (int j = 0; j < selectedColumns.length; j++) {
                        selectedData = (String) jTable1.getValueAt(selectedRow[i], selectedColumns[j]);
                    }
                }
                updateInfo(selectedData);
            }

        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ndtimkiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 266, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(27, 27, 27)
                                    .addComponent(jButton2)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton6)
                                .addComponent(jButton4))))
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ndtimkiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ndtimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ndtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addbutton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String toDay(){
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date =new Date(System.currentTimeMillis()-24*60*60*1000);
        return dateFormat.format(date).toString();
        
    }
    private String toYesterday(){
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date(System.currentTimeMillis()-2*24*60*60*1000);
        return dateFormat.format(date).toString();
    }
    private String toTwodaybefore(){
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date(System.currentTimeMillis()-3*24*60*60*1000);
        return dateFormat.format(date).toString();
    }
    
    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter databasExtensionFilter = new FileNameExtensionFilter("tệp tùy chỉnh", "excel");
        fileChooser.setFileFilter(databasExtensionFilter);
        fileChooser.setMultiSelectionEnabled(false);
        
        int x = fileChooser.showDialog(this, "open");
        if(x == JFileChooser.APPROVE_OPTION){
            File f = fileChooser.getSelectedFile();
            ImportToDatabase itd = new ImportToDatabase(f.getAbsolutePath());
            if(itd.codeStat != -1){
                this.jTextArea1.setText("import file success!");
            }
            else {
                this.jTextArea1.setText("import file fail because your file is not right format! (eg: *HNX,HSX,UPCOM*.xlsx)");
            }
        }
    }//GEN-LAST:event_addbuttonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if ((evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)) {
            int selection = this.jComboBox1.getSelectedIndex();
            switch (selection){
            case 0:{  
                    setMa_CP("select Ma_CP from So_Lieu_Giao_Dich where San_GD = 'HNX'");
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    this.Ma_CP,
                    new String [] {
                        "Mã Cổ Phiếu Hiện GD"
                    }
                    ) {
                        Class[] types = new Class [] {
                            java.lang.String.class
                        };
                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types [columnIndex];
                        }
                    });
                    break;
            }
            case 1:{  
                    setMa_CP("select Ma_CP from So_Lieu_Giao_Dich where San_GD = 'HSX'");
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    this.Ma_CP,
                    new String [] {
                        "Mã Cổ Phiếu Hiện GD"
                    }
                    ) {
                        Class[] types = new Class [] {
                            java.lang.String.class
                        };
                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types [columnIndex];
                        }
                    });
                    break;
            }
            case 2:{  
                    setMa_CP("select Ma_CP from So_Lieu_Giao_Dich where San_GD = 'UPCOM'");
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    this.Ma_CP,
                    new String [] {
                        "Mã Cổ Phiếu Hiện GD"
                    }
                    ) {
                        Class[] types = new Class [] {
                            java.lang.String.class
                        };
                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types [columnIndex];
                        }
                    });
                    break;
            }  }
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String text = jButton1.getText();
        long date = Long.parseLong(text.substring(0,2)) + Long.parseLong(text.substring(3,5)) * 100 + Long.parseLong(text.substring(6,10)) * 10000;
        //date = 20201112;   //for test 
        if(this.selectedCP == null){
            this.jTextArea1.setText("Xin hãy chọn Mã Cổ Phiếu trước");
            return;
        }
        else{
             String query = "select * from So_Lieu_Giao_Dich where Ma_CP = '"
                + this.selectedCP + "'"
                + " and Ngay_GD = " + String.valueOf(date);
            this.updateInfoFinal(query);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String text = jButton1.getText();
        long date = Long.parseLong(text.substring(0,2)) + Long.parseLong(text.substring(3,5)) * 100 + Long.parseLong(text.substring(6,10)) * 10000;
        //date = 20201112;   //for test 
        if(this.selectedCP == null){
            this.jTextArea1.setText("Xin hãy chọn Mã Cổ Phiếu trước");
            return;
        }
        else{
             String query = "select * from So_Lieu_Giao_Dich where Ma_CP = '"
                + this.selectedCP + "'"
                + " and Ngay_GD = " + String.valueOf(date);
            this.updateInfoFinal(query);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String text = jButton1.getText();
        long date = Long.parseLong(text.substring(0,2)) + Long.parseLong(text.substring(3,5)) * 100 + Long.parseLong(text.substring(6,10)) * 10000;
        //date = 20201112;   //for test 
        if(this.selectedCP == null){
            this.jTextArea1.setText("Xin hãy chọn Mã Cổ Phiếu trước");
            return;
        }
        else{
             String query = "select * from So_Lieu_Giao_Dich where Ma_CP = '"
                + this.selectedCP + "'"
                + " and Ngay_GD = " + String.valueOf(date);
            this.updateInfoFinal(query);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String selectedData = this.jTextField1.getText();
        if(selectedData == null){
            this.jTextArea1.setText("Mời bạn điền mã Cổ Phiếu trước khi Search");
        }
        else{
            updateInfo(selectedData);
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    
    
    private void setMa_CP(String query){
        ResultSet rs = this.db.executeQuerySelect(query);
        if (rs == null){
            this.Ma_CP = null;
        }else{
            String tmp[][] = new String[300][1];
            int i = 0;
            try {
                while(rs.next()) {
                    tmp[i][0] = rs.getString(1);
                    i++; 
                }
            }catch(SQLException e) {
                    e.getStackTrace();
            }
            this.Ma_CP = new String[i][1];
            for(int j = 0; j < i ;j++){
                this.Ma_CP[j][0] = tmp[j][0];
            }
        }
            
    }
    
    private void updateInfo(String selectedData){
        
        if(this.selectedCP != null && this.selectedCP.compareTo(selectedData) == 0) return;
        String query = "select * from So_Lieu_Giao_Dich where Ma_CP = '"
                +selectedData + "'";
        ResultSet rs = this.db.executeQuerySelect(query);
        String out = null;
        try {
                while(rs.next()) {
                    out = "Ma co phieu : " + rs.getString(1);
                    break;
                }
        }catch(SQLException e) {
                    e.getStackTrace();
            }
        this.selectedCP = selectedData;
        if(out == null) return;
        this.jTextArea1.setText(out);
        
    }
    
    private void updateInfoFinal(String query){
        System.out.println(query);
        ResultSet rs = this.db.executeQuerySelect(query);
        String out = null;
        try {
                while(rs.next()) {
                    out = "ngay GD : " + String.valueOf((long)rs.getDouble(2));
                    break;
                }
        }catch(SQLException e) {
                    e.getStackTrace();
            }
        if(out == null) return;
        this.jTextArea1.setText(out);
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demogiaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demogiaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demogiaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demogiaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demogiaodien().setVisible(true);
            }
        });
    }

    private ConnectDatabase db = new ConnectDatabase();
    private String[][] Ma_CP = null;
    private String selectedCP = null;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel ndtimkiem;
    private javax.swing.JLabel ndtimkiem1;
    // End of variables declaration//GEN-END:variables
}
