/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JComboBox;
import java.util.ArrayList;
import java.util.List;

import java.sql.ResultSet;
import java.sql.SQLException;
import processdata.ConnectDatabase;
import processdata.ImportToDatabase;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author Admin
 */
public class demogiaodien extends javax.swing.JFrame {

    /**
     * Creates new form demogiaodien
     */
    public demogiaodien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        ndtimkiem = new javax.swing.JLabel();
        addbutton = new javax.swing.JButton();
        ndcodinh = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("thông tin cổ phiếu");
        setBackground(new java.awt.Color(255, 102, 51));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 800));

        ndtimkiem.setBackground(new java.awt.Color(102, 204, 255));
        ndtimkiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ndtimkiem.setForeground(new java.awt.Color(0, 153, 51));
        ndtimkiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ndtimkiem.setText("NỘI DUNG TÌM KIẾM");
        ndtimkiem.setOpaque(true);

        addbutton.setBackground(new java.awt.Color(102, 102, 0));
        addbutton.setForeground(new java.awt.Color(204, 204, 255));
        addbutton.setText("import data");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        ndcodinh.setBackground(new java.awt.Color(153, 153, 153));
        ndcodinh.setPreferredSize(new java.awt.Dimension(462, 200));

        jLabel3.setText("TYPE");

        jLabel1.setText("CHOOSEN TAGS:");

        jComboBox2.setMaximumRowCount(14);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn nội dung:", "Nhà đầu tư nước ngoài", "Cổ phiếu nổi bật", "Cổ phiếu ngân hàng chốt phiên", "Thanh khoản", "Giao dịch thỏa thuận/chuyển nhượng thỏa thuận", "Đặc tính Nổi bật", "Khối ngoại", "Cổ phiếu chứng khoán", "Cổ phiếu ngân hàng", "Cổ phiếu Penny và midcap", "Tổng hợp theo thời gian", "Kỷ lục", "Bán ra/mua lại" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton5.setText("Choose");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel2.setText("TAG");

        jComboBox3.setMaximumRowCount(15);
        jComboBox3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jComboBox3ComponentAdded(evt);
            }
        });

        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ndcodinhLayout = new javax.swing.GroupLayout(ndcodinh);
        ndcodinh.setLayout(ndcodinhLayout);
        ndcodinhLayout.setHorizontalGroup(
            ndcodinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ndcodinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ndcodinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ndcodinhLayout.createSequentialGroup()
                        .addGroup(ndcodinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ndcodinhLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ndcodinhLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(216, 216, 216))))
        );
        ndcodinhLayout.setVerticalGroup(
            ndcodinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ndcodinhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ndcodinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(102, 204, 255));
        jTabbedPane1.setForeground(new java.awt.Color(153, 153, 255));
        jTabbedPane1.setOpaque(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ngày", jPanel4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sàn giao dịch - Hà Nội (default):", "TP.Hồ Chí Minh", "UPCOM" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        this.setMa_CP("select Ma_CP from So_Lieu_Giao_Dich where San_GD = 'HNX'");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            this.Ma_CP,
            new String [] {
                "Mã Cổ Phiếu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setFillsViewportHeight(true);
        jTable1.setFocusable(false);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("");
        jTable1.setCellSelectionEnabled(true);
        ListSelectionModel cellSelectionModel = jTable1.getSelectionModel();
        cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        cellSelectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String selectedData = null;

                int[] selectedRow = jTable1.getSelectedRows();
                int[] selectedColumns = jTable1.getSelectedColumns();

                for (int i = 0; i < selectedRow.length; i++) {
                    for (int j = 0; j < selectedColumns.length; j++) {
                        selectedData = (String) jTable1.getValueAt(selectedRow[i], selectedColumns[j]);
                    }
                }
                updateInfo(selectedData);
            }

        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(989, 989, 989)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("mã", jPanel5);
        jPanel5.getAccessibleContext().setAccessibleName("");
        jPanel5.getAccessibleContext().setAccessibleDescription("");

        jTextArea1.setBackground(new java.awt.Color(153, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setForeground(new java.awt.Color(204, 204, 255));
        jButton1.setText("exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ndtimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)))
                .addGap(18, 18, 18)
                .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addComponent(ndcodinh, javax.swing.GroupLayout.DEFAULT_SIZE, 1296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ndtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addbutton)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(ndcodinh, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        ndcodinh.getAccessibleContext().setAccessibleDescription("");
        jTabbedPane1.getAccessibleContext().setAccessibleName("ngày");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed


        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter databasExtensionFilter = new FileNameExtensionFilter("tệp tùy chỉnh", "excel");
        fileChooser.setFileFilter(databasExtensionFilter);
        fileChooser.setMultiSelectionEnabled(false);
        
        int x = fileChooser.showDialog(this, "open");
        if(x == JFileChooser.APPROVE_OPTION){
            File f = fileChooser.getSelectedFile();
            ImportToDatabase itd = new ImportToDatabase(f.getAbsolutePath());
            if(itd.codeStat != -1){
                this.jTextArea1.setText("import file success!");
            }
            else {
                this.jTextArea1.setText("import file fail because file is not right format!");
            }
        }
        
    }//GEN-LAST:event_addbuttonActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(null);
        jTextArea2.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
         if ((evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)) {
            int selection = this.jComboBox1.getSelectedIndex();
            switch (selection){
            case 0:{  
                    setMa_CP("select Ma_CP from So_Lieu_Giao_Dich where San_GD = 'HNX'");
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    this.Ma_CP,
                    new String [] {
                        "Mã Cổ Phiếu Hiện GD"
                    }
                    ) {
                        Class[] types = new Class [] {
                            java.lang.String.class
                        };
                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types [columnIndex];
                        }
                    });
                    break;
            }
            case 1:{  
                    setMa_CP("select Ma_CP from So_Lieu_Giao_Dich where San_GD = 'HSX'");
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    this.Ma_CP,
                    new String [] {
                        "Mã Cổ Phiếu Hiện GD"
                    }
                    ) {
                        Class[] types = new Class [] {
                            java.lang.String.class
                        };
                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types [columnIndex];
                        }
                    });
                    break;
            }
            case 2:{  
                    setMa_CP("select Ma_CP from So_Lieu_Giao_Dich where San_GD = 'UPCOM'");
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    this.Ma_CP,
                    new String [] {
                        "Mã Cổ Phiếu Hiện GD"
                    }
                    ) {
                        Class[] types = new Class [] {
                            java.lang.String.class
                        };
                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types [columnIndex];
                        }
                    });
                    break;
            }  }
         }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        listTag.remove(listTag.size()-1);
        jTextArea2.removeAll();
        jTextArea2.setText(null);
        for( String s : listTag){
            jTextArea2.setText(jTextArea2.getText()+' '+';'+' '+s);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jComboBox3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ComponentAdded

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String tmp = (String) jComboBox3.getSelectedItem();
        listTag.add(tmp);
        jTextArea2.setText(jTextArea2.getText()+' '+';'+' '+tmp);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        switch(jComboBox2.getSelectedIndex()){
            case 1:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag1.length;i++){
                jComboBox3.addItem(tag1[i]);
            }
            break;
            case 2:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag2.length;i++){
                jComboBox3.addItem(tag2[i]);
            }
            break;
            case 3:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag3.length;i++){
                jComboBox3.addItem(tag3[i]);
            }
            break;
            case 4:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag4.length;i++){
                jComboBox3.addItem(tag4[i]);
            }
            break;
            case 5:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag5.length;i++){
                jComboBox3.addItem(tag5[i]);
            }
            break;
            case 6:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag6.length;i++){
                jComboBox3.addItem(tag6[i]);
            }
            break;
            case 7:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag7.length;i++){
                jComboBox3.addItem(tag7[i]);
            }
            break;
            case 8:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag8.length;i++){
                jComboBox3.addItem(tag8[i]);
            }
            break;
            case 9:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag9.length;i++){
                jComboBox3.addItem(tag9[i]);
            }
            break;
            case 10:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag10.length;i++){
                jComboBox3.addItem(tag10[i]);
            }
            break;
            case 11:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag11.length;i++){
                jComboBox3.addItem(tag11[i]);
            }
            break;
            case 12:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag12.length;i++){
                jComboBox3.addItem(tag12[i]);
            }
            break;
            case 13:
            jComboBox3.removeAllItems();
            for(int i = 0; i < tag13.length;i++){
                jComboBox3.addItem(tag13[i]);
            }
            break;
            default:
            jComboBox3.removeAllItems();
            break;
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    
    private void setMa_CP(String query){
        ResultSet rs = this.db.executeQuerySelect(query);
        if (rs == null){
            this.Ma_CP = null;
        }else{
            String tmp[][] = new String[300][1];
            int i = 0;
            try {
                while(rs.next()) {
                    tmp[i][0] = rs.getString(1);
                    i++; 
                }
            }catch(SQLException e) {
                    e.getStackTrace();
            }
            this.Ma_CP = new String[i][1];
            for(int j = 0; j < i ;j++){
                this.Ma_CP[j][0] = tmp[j][0];
            }
        }
            
    }
    
    private void updateInfo(String selectedData){
        
        if(this.selectedCP != null && this.selectedCP.compareTo(selectedData) == 0) return;
        String query = "select * from So_Lieu_Giao_Dich where Ma_CP = '"
                +selectedData + "'";
        ResultSet rs = this.db.executeQuerySelect(query);
        String out = null;
        try {
                while(rs.next()) {
                    out = "Ma co phieu : " + rs.getString(1);
                    break;
                }
        }catch(SQLException e) {
                    e.getStackTrace();
            }
        this.selectedCP = selectedData;
        if(out == null) return;
        this.jTextArea1.setText(out);
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demogiaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demogiaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demogiaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demogiaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demogiaodien().setVisible(true);
            }
        });
    }
    private ConnectDatabase db = new ConnectDatabase();
    private String[][] Ma_CP = null;
    private String selectedCP = null;
    
    private String[] tag1 = {"Nhà đầu tư nước ngoài"};
    private String[] tag2 = {"Giao dịch lớn","Tỷ lệ % giao dịch cổ phiếu lớn","Tỷ lệ % giao dịch thấp – cổ phiếu kém",
                             "Nhận định chung","Cổ phiếu hot bán ra","Cổ phiếu hot gom vào/mua vào",
                             "Cổ phiếu hot","Giao dịch vượt ngưỡng","Cổ phiếu mức khá",
                             "Cổ phiếu tăng nhẹ","Cổ phiếu giảm giá","So sánh cổ phiếu","So sánh theo thời gian",
                             "Phân tích 1 cổ phiếu","So sánh 2 sàn",};
    private String[] tag3 = {"Cổ phiếu ngân hàng, chốt phiên"};
    private String[] tag4 = {"Thanh khoản","Tổng giá trị giao dịch","Tăng trần",
                            "Dư bán","Dư mua","Đứng giá","Tiêu cực","Chuyển nhượng/khớp lệnh"};
    private String[] tag5 = {"Giao dịch thỏa thuận/chuyển nhượng thỏa thuận"};
    private String[] tag6 = {"Đặc tính Nổi bật","Khác biệt với xu thế chung"};
    private String[] tag7 = {"Khối ngoại"};
    private String[] tag8 = {"Cổ phiếu chứng khoán"};
    private String[] tag9 = {"Cổ phiếu ngân hàng"};
    private String[] tag10 = {"Cổ phiếu Penny, midcap"};
    private String[] tag11 = {"Long term","Short term"};
    private String[] tag12 = {"Kỷ lục"};
    private String[] tag13 = {"Bán ra/mua lại"};
    private List<String> listTag = new ArrayList<String>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel ndcodinh;
    private javax.swing.JLabel ndtimkiem;
    // End of variables declaration//GEN-END:variables
}
